# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\"9\n\x0fRegisterRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0buser_passwd\x18\x02 \x01(\t\"B\n\rRegisterReply\x12!\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x13.RegisterCodeResult\x12\x0e\n\x06reason\x18\x02 \x01(\t\"6\n\x0cLoginRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0buser_passwd\x18\x02 \x01(\t\"K\n\nLoginReply\x12\x1e\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x10.LoginCodeResult\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x15\n\x04ping\x12\r\n\x05token\x18\x01 \x01(\t\"\x06\n\x04pong*c\n\x12RegisterCodeResult\x12\x11\n\rRCR_undefined\x10\x00\x12\n\n\x06RCR_ok\x10\x01\x12\x15\n\x11RCR_already_exist\x10\x02\x12\x17\n\x13RCR_bad_credentials\x10\x03*_\n\x0fLoginCodeResult\x12\x11\n\rLCR_undefined\x10\x00\x12\n\n\x06LCR_ok\x10\x01\x12\x14\n\x10LCR_unknown_user\x10\x02\x12\x17\n\x13LCR_bad_credentials\x10\x03\x32\x7f\n\x07Greeter\x12.\n\x08Register\x12\x10.RegisterRequest\x1a\x0e.RegisterReply\"\x00\x12%\n\x05Login\x12\r.LoginRequest\x1a\x0b.LoginReply\"\x00\x12\x1d\n\x07\x43onnect\x12\x05.ping\x1a\x05.pong\"\x00(\x01\x30\x01\x62\x06proto3')

_REGISTERCODERESULT = DESCRIPTOR.enum_types_by_name['RegisterCodeResult']
RegisterCodeResult = enum_type_wrapper.EnumTypeWrapper(_REGISTERCODERESULT)
_LOGINCODERESULT = DESCRIPTOR.enum_types_by_name['LoginCodeResult']
LoginCodeResult = enum_type_wrapper.EnumTypeWrapper(_LOGINCODERESULT)
RCR_undefined = 0
RCR_ok = 1
RCR_already_exist = 2
RCR_bad_credentials = 3
LCR_undefined = 0
LCR_ok = 1
LCR_unknown_user = 2
LCR_bad_credentials = 3


_REGISTERREQUEST = DESCRIPTOR.message_types_by_name['RegisterRequest']
_REGISTERREPLY = DESCRIPTOR.message_types_by_name['RegisterReply']
_LOGINREQUEST = DESCRIPTOR.message_types_by_name['LoginRequest']
_LOGINREPLY = DESCRIPTOR.message_types_by_name['LoginReply']
_PING = DESCRIPTOR.message_types_by_name['ping']
_PONG = DESCRIPTOR.message_types_by_name['pong']
RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterReply = _reflection.GeneratedProtocolMessageType('RegisterReply', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREPLY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:RegisterReply)
  })
_sym_db.RegisterMessage(RegisterReply)

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:LoginRequest)
  })
_sym_db.RegisterMessage(LoginRequest)

LoginReply = _reflection.GeneratedProtocolMessageType('LoginReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREPLY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:LoginReply)
  })
_sym_db.RegisterMessage(LoginReply)

ping = _reflection.GeneratedProtocolMessageType('ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:ping)
  })
_sym_db.RegisterMessage(ping)

pong = _reflection.GeneratedProtocolMessageType('pong', (_message.Message,), {
  'DESCRIPTOR' : _PONG,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:pong)
  })
_sym_db.RegisterMessage(pong)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERCODERESULT._serialized_start=307
  _REGISTERCODERESULT._serialized_end=406
  _LOGINCODERESULT._serialized_start=408
  _LOGINCODERESULT._serialized_end=503
  _REGISTERREQUEST._serialized_start=16
  _REGISTERREQUEST._serialized_end=73
  _REGISTERREPLY._serialized_start=75
  _REGISTERREPLY._serialized_end=141
  _LOGINREQUEST._serialized_start=143
  _LOGINREQUEST._serialized_end=197
  _LOGINREPLY._serialized_start=199
  _LOGINREPLY._serialized_end=274
  _PING._serialized_start=276
  _PING._serialized_end=297
  _PONG._serialized_start=299
  _PONG._serialized_end=305
  _GREETER._serialized_start=505
  _GREETER._serialized_end=632
# @@protoc_insertion_point(module_scope)
